### ISSUE TITLE
Pass persistently stored items to subprotocols

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#180]
Right now, each subprotocol takes the entire blob of persistent storage and retrieves/stores data that it needs as it goes through the protocol. However, this seems gratuitous; it would be better to pull out the specific fields that the protocol needs to execute correctly and return any values that need to be stored persistently at the end, without giving free access to the entire storage.

## Proposed solution

The `ProtocolParticipant` trait method `process_message` takes `main_storage: Storage` as a parameter right now. Instead, the trait should define an associated type with the persistent-storage inputs it expects, and take this type as a parameter. This will be different for each subprotocol.

Granularity: I think the most reasonable approach is to pull out all the persistent storage items used in a protocol at the `Participant` level and pass them to the subprotocol, regardless of which round we're at. This will come at a slight efficiency cost (e.g. in round 1 of a protocol, we might not need every bit of persistent storage; some of it might not be used until round 3) but my initial take is that it's neater than trying to parse the message type further in `Participant::process_message` to determine what items are needed for a specific message. Also, any inefficiency will become irrelevant when we refactor out main storage, so it's not worth optimizing right now.

Returning values: keygen and auxinfo both place output values directly into storage. After #193 and #194 are complete, they will _also_ return those values as output. Be sure to remove the main storage insertions!

## Closing criteria
- [x] Extract all calls to retrieve items from persistent storage from subprotocol participants and move them into the main `Participant` driver function -- done as of #245
- [x] #229
- [x] Remove `main_storage` from the `ProtocolParticipant` API and update `storage` calls to return local storage. (#222)
- [x] Update `process_ready_message` to store the relevant message internally, instead of externally.
- [x] Add "inputs from persistent storage" associated type to `ProtocolParticipant` -- done in #235
- [x] write some test that can adequately express the correct behavior?? -- added e2e tests in #235
- [x] Revisit documentation on `ProcessOutput` and update it with any additional context from how it's now used. -- this type is not updated to be external-facing, so its documentation seems fine.

**Comment by marsella** [comment]
The long game should have main storage elements be a public parameter from the calling application, and outputs returned to the calling application. I think this is still a useful intermediate step to get persistent storage out of the protocol implementation, though.

**Comment by amaloz** [comment]
I added #226 as an intermediate step towards achieving this in order to make the eventual PR more manageable.

**Comment by marsella** [comment]
I added #236 as another intermediary step.

**Comment by marsella** [comment]
I'm closing this as completed by #235 and #245.
