### ISSUE TITLE
Make Paillier encryption more misuse-resistant

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#21]
The Paillier signing API would benefit from improving overall code quality for two main reasons. First, adding misuse resistance, to make sure developers are able to use Paillier methods and types correctly and easily. Second, improving abstraction, to make it easier in the future to change the underlying Paillier dependency without having to interact with every spot in the code that uses it.

The primary change is to enforce abstraction-layer types, rather than underlying or raw types. For example, encryption returns "raw" `BigNumber`s for the ciphertext and the nonce. In most places where encryption is called, though, the ciphertext results are wrapped in the `PaillierCiphertext` type for all subsequent uses. In the places where it's not wrapped in the ciphertext type, it's used in proofs that do expect a ciphertext (e.g. not an arbitrary big number).

There are also several API improvements described below that could reduce the possibility of callers instantiating key types incorrectly.

To complete this issue:
- [x] (#59) Update the `encrypt` and `decrypt` functions in the Paillier module to return and take `PaillierCiphertext`s directly.

- [x] (#63) Update any proofs that expect Paillier ciphertexts as input to encode those explicitly, rather than as `BigNumber`s. I spotted some by following the `encrypt`ions, but I'm not sure if this is exhaustive:
- `PiAffg` (Paillier Operation with Group Commitment in Range ZK): input `Y` is a ciphertext
- `PiEnc` (Paillier Encryption in Range ZK): input `K` is a ciphertext, but this is already encoded!
- `PiLog` (Knowledge of Exponent vs Paillier Encryption): I think input `C` is a ciphertext, but the proof definition (Fig 25) is kind of vague on this.

- [x] (#61) Refactor `encrypt` to call the `libpaillier::EncryptionKey` `encrypt` function. Unless this is an intentional reimplementation, in which case we should document why this version is better.
- [x] (#62) Paillier encryption returns a ciphertext and a nonce. It looks like the nonce is also typically used as a secret input to proofs -- can we similarly create a custom `PaillierNonce` wrapper and propagate that throughout the proofs?

- [x] (#60) Make a utility method for generating a pair of encryption / decryption keys and replace all manual wrapping / calls to `with_safe_primes_unchecked` with it. Also, revisit whether we want the unchecked generation call.
