### ISSUE TITLE
Add a `remove` method to `LocalStorage`

### ISSUE THREAD

**Issue by amaloz** [boltlabs-inc/tss-ecdsa#288]
Several items stored in `LocalStorage` are private, and it would be better if we could remove them from `LocalStorage` when needed, rather than just `retrieve` them.

# Tasks
- [ ] Add `remove` method to `LocalStorage`
- [ ] Write documentation / guidance for its use (e.g., when pulling secrets out of local storage to return them to the user)
- [ ] Call it in all appropriate places across the protocols
- [ ] Remove extra clones that are no longer needed
