### ISSUE TITLE
Add `BroadcastOutput::extract_message` method

### ISSUE THREAD

**Issue by amaloz** [boltlabs-inc/tss-ecdsa#291]
We see the following code pattern crop up in the various protocol implementations:
```rust
        if broadcast_message.tag != BroadcastTag::KeyGenR1CommitHash {
            return Err(InternalError::IncorrectBroadcastMessageTag);
        }
        let message = &broadcast_message.msg;
```
It'd be better to encapsulate this into a method on `BroadcastOutput` such as:
```rust
pub(crate) fn extract_message(&self, expected_tag: BroadcastTag) -> Result<&Message>
```

# Tasks
- [x] Implement `extract_message` method
- [x] Make the `msg` and `tag` fields on `BroadcastOutput` private, if possible
- [x] Replace existing hand-rolled code with new method

**Comment by marsella** [comment]
Thought: I think this usually is the last thing we do with the `broadcast_message`, so the function will probably be able to consume it instead of taking by reference. In that case, we can call it straight-up `into_message`.
