### ISSUE TITLE
Replace `from_message` with `TryFrom`

### ISSUE THREAD

**Issue by amaloz** [boltlabs-inc/tss-ecdsa#297]
In multiple places we implement a `from_message(message: &Message) -> Result<Self>` method. It'd be more canonical if we used `TryFrom<Message>` here instead.

# Tasks
- [ ] Replace `from_message` with `TryFrom` in `keygen` module
- [ ] Replace `from_message` with `TryFrom` in `auxinfo` module
- [ ] Replace `from_message` with `TryFrom` in `presign` module

**Comment by marsella** [comment]
Several related issues: 
- #32 focuses on making sure these bytes -> interesting types functions actually check everything that needs to be checked. This issue is only about canonicalizing the API. 
- #214. The `from_message` methods in presign actually do a bunch of protocol work instead of just converting message bytes to meaningful types. 214 includes refactoring those calls into two methods, one to convert and check type validity (`from_message` / `try_from`), and one to do the protocol steps.
