### ISSUE TITLE
Introduce a `HashCommitment` API to promote code-reuse.

### ISSUE THREAD

**Issue by amaloz** [boltlabs-inc/tss-ecdsa#345]
Currently, both `keygen` and `auxinfo` make use of a hash-based commitment scheme. These two implementations however are independent and don't necessarily share a common API, even though at a fundamental level they are doing the same thing. The idea with this issue is to introduce a `HashCommitment` trait that can encapsulate the core hash-based commitment scheme functionality. Then, both the `keygen` and `auxinfo` constructions can implement this trait.

In terms of priority, I'd say this is quite low priority, since I believe only those two protocols make use of such a commitment scheme, so it'd be important to weight the potential added complexity of a new trait with the simplification of the internal commitment scheme API.

# Tasks
- [ ] Explore whether introducing a `HashCommitment` trait is worth it.

If so:
- [ ] Implement the `HashCommitment` trait
- [ ] Update the `keygen` commitment to use the `HashCommitment` trait.
- [ ] Update the `auxinfo` commitment to use the `HashCommitment` trait.
