### ISSUE TITLE
Refactor `PresignRecord`

### ISSUE THREAD

**Issue by amaloz** [boltlabs-inc/tss-ecdsa#360]
Improve the documentation, type names, and control flow of `PresignRecord`.

# Tasks
- [ ] Refactor the type names to make the module more readable for someone not well versed in the paper.
- [ ] Write documentation on how `PresignRecord` works, and document each method within `PresignRecord`.
- [ ] Modify the control flow to have a clear separation of `PresignRecord` with the core `presign` code. In particular, move functionality in `PresignRecord::try_from` to the main `presign` implementation to better match the paper.
