### ISSUE TITLE
Figure out handling of elements in Z*_N

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#40]
There are several places in the code where a variable is expected to be in the multiplicative group `Z*_N`. For our composite moduli `N = p*q`, this means that the variable must be relatively prime to `N` (incl. non-zero) and should be smaller than `N`. Treatment of these values varies throughout the library, but in general, variables expected to be in this group are encoded as `BigNumber`, and are (inconsistently?) checked at use-time to see if they're non-zero.

It would be better to have some kind of compile-time guarantee that values are in the expected group. Checking non-zero values is pretty straightforward. However, checking that the value is canonical (e.g. smaller than `N` and relatively prime to `N`) is harder because there are many different moduli used and I think some of them are not hard-coded parameters (e.g. parties choose a Paillier-Blum modulus at runtime).

## Proposed solution
We could take a leaf out of the `unknown_order` crate's book and _not_ encode the modulus into the type. This crate provides the `BigNumber` type and all the methods necessary to do group operations with a specified modulus, but don't encode the order of a given variable into the variable itself.

With this, we would have a controlled constructor to draw a new element in `Z*N` at random and a verify function that can be used when deserializing (see #32) potential elements in the group. These functions would both take the expected modulus as a parameter. This maintains the status quo of requiring runtime validation of types but will move those checks to the point of type instantiation, and avoids the developer having to figure out if and when a value needs to be validated.
```rust
struct ZStar(BigNumber);
impl ZStar {
    /// Check that value is non-zero, less than `modulus`, and relatively prime to `modulus`.
    fn verify(&self, modulus: BigNumber) {...}

    /// Create new canonically-formed element in `ZStar`
    fn new(value: BigNumber, modulus: BigNumber) -> Result<Self, Error> {...}
}
```

This option isn't set in stone and can be modified.

## Tasks

To close this issue:
- [ ] Design a reasonable approach and document it in the comments
- [ ] Implement approach
- [ ] Test approach, especially generation and deserialization methods
- [ ] ~Replace all instances of `BigNumber`s that should be `ZStar`s~ - this is moved to #132

**Comment by marsella** [comment]
Adding this to the #80 epic because it blocks the task in a variety of proofs to "make proof input types more specific".

**Comment by marsella** [comment]
This PR should include removing extra validation steps that are currently sprinkled throughout the code, like checking if the nonce is 0 after calling Paillier encryption.

**Comment by marsella** [comment]
An open question for me is how to handle this type on deserialization. Should we write a custom `serde::Deserialize` method that checks for coprimality? Or allow this to deserialize from any appropriately-denoted `BigNumber` and require the user to manually call `verify` to make sure it is _actually_ in `ZStar`? The former sounds more correct, but then deserialization would require knowledge of the modulus, which I think doesn't work with the normal `serde` APIs.

**Comment by gatoWololo** [comment]
> Should we write a custom serde::Deserialize method that checks for coprimality
While `serde` is awesome, I have found trying to write custom serde instances painful.

One possible solution, if I'm understanding what you want correctly:
```rust
/// Your main type which is guaranteed to be verified by construction.
/// Has a method `serialize` for serializing but not method to create one from deserialize data.
struct ZStarN {
    inner: ZStarN,
}

// Allow value to be serialized.
impl ZStarN {
    fn serialize(self) -> Vec<u8> {
        todo!("Call serialize on self.inner")
    }
}

// Inner type used so both the verified and unverified type have the same representation. 
#[derive(Serialize, Deserialize)]
struct ZStarNInner {
    n: BigNumber,
    value: BigNumber,
    ... // whatever else
}

// User can only deserialize into a `ZStarNUnverfied` instance. They must call tryfrom instance below to create a proper `ZStarN`
#[derive(Serialize, Deserialize)]
struct ZStarNUnverfied {
    values: ZStarNInner,
}

Check the values here and error if verification fails.
impl TryFrom<ZStarNUnverfied> for ZStarN {
    type Error = ...;

    fn try_from(value: ZStarNUnverfied) -> Result<Self, Self::Error> {
        todo!()
    }
}
```

**Comment by marsella** [comment]
Ooh, I like this approach! All the convenience of derivable serde, while still forcing the caller to verify the `Unverified` type before they can use it. 

My only nit is that I think we don't want to encode `N` into `ZStarN` directly -- it'll double the size of the type (and these will be sent over the network / enclave boundary, where it matters), and the caller will have to provide `N` either way, to make sure that it's the `N` they expect.

**Comment by amaloz** [comment]
Here is one suggested approach to avoid needing to encode `N` into `ZStarN`. The idea is to have a `ZStarNBuilder`, defined something like:
```rust
struct ZStarNBuilder {
    N: BigNumber
    // ...
}

impl ZStarNBuilder {
    pub validate(&self, ZStarNUnverified) -> ZStarN;
    // ...
}
```
Now, `ZStarN` is defined with the builder attached:
```rust
struct ZStarN<'a> {
    value: BigNumber,
    builder: &'a ZStarNBuilder,
}
```
We can then define functions like `add` and `multiply` on `ZStarN` that use the builder internally to enforce consistency.

**Comment by marsella** [comment]
@Ra1issa I rewrote one of our epics to be all about handling deserialization appropriately (#6). It seems to me like there's been some scope creep and this issue is getting massive. If you haven't done the deserialization stuff yet, I think it would make sense to separate that into a separate issue and PR, and focus on defining the type and usage API correctly for now.
