### ISSUE TITLE
Improve code quality for PiSchProof

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#52]
Note: This issue has expanded since it was first written; it might be appropriate to break it into several separate issues.

---
There are a few code quality issues for `PiSchProof`.

- [ ] Add top-level documentation to `PiSchProof` explaining what statements it proves
- [ ] Update field names for proof, precommit, input, public params, and secret to have meaningful context where possible, and update the field docs with the short names (#389)
- [ ] Update field types to more meaningful types where possible
- [ ] Refactor `prove` to use the helper `precommit` and `prove_from_precommit` functions to reduce code duplication (#390)
- [ ] Remove constants from inputs. The curve parameters `q` and `g` are fixed across the implementation and don't have to be parameters to this proof. (#388)
- [ ] Align type names with other refactored ZKPs, including changing input + secret names to `CommonInput` and `ProverSecret` (#390)
- [ ] For inputs to the common input and prover secrets that are always actually key share types, update them to take (e.g.) `AsRef<BigNumber>` instead of a straight `BigNumber`, or make the common and secret input associated types be exactly the key shares (rather than wrappers around them). (#388)

Putting a blocker on #49 to avoid divergence between plain and `with_transcript` methods.
