### ISSUE TITLE
Design appropriate session ID abstractions

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#91]
The CCGMP protocol itself defines several different types of cryptographic session identifiers, corresponding to different participant groups, generated keys, and signing instances. These may be independent from programmatically-necessary unique identifiers (e.g. database IDs). Our calling application may have further identifiers (e.g. for end users) as well as mappings between identifiers (e.g. for a given client, what keys do they have available and are there any in-process signatures).

This epic has several goals:
- [x] Make sure that the protocol implementation correctly defines and uses session IDs as described in the paper, and documents any intentional deviations. If appropriate, design an updated scheme to create and distribute IDs in a misuse-resistant, secure way and, after internal review, define an epic and issues to handle the refactor.
- [x] Determine which identifiers should be generated internally (e.g. as part of the tss-ecdsa library) vs by the calling application, and make sure these distinctions are clearly documented. Implement any necessary abstractions to enforce this boundary.
- [ ] ~Determine and document what identifier mappings need to be maintained by the calling application.~ This is now handled by issue #218 in epic #148.

Related issues: #18

--- 
Terminology
- "session": A run of keygen + aux-info
- "subsession": A run of presign or sign
- "session identifier" or "subsession identifier": unique identifier for a single instance of a session or subsession. These terms are not used consistently across the issues, but they're intended to be the same thing.
- "protocol identifier": describes which session or subsession is running; this is the same across different instantiations
- asset owner: the party that wants a signature under a key
- participants: aka key servers, aka signers. The parties that hold key shares and participate in CGGMP protocol executions.
- coordinator: a potential system component that will sit between the asset owner and the participants. They will serve as a router at least; they might also serve other functionalities. We haven't settled on a threat model for this role.

**Comment by marsella** [comment]
Updated title and description to capture this a bit better.

**Comment by indomitableSwan** [comment]
From my internal notes:

We need to revamp session identifiers (sid and ssid) in the tss-ecdsa protocol and make sure that the implementation correctly covers the functionalities from the paper separately, i.e. We need
1. Proper, unique session identifiers that aren't just tuples of public parameters (which is the case in the paper)
1. To make sure that ZK proofs  are bound to sessions via these (actual) unique session identifiers
1. To bind the appropriate public values from sid, ssid (i.e., statements) to our ZK proofs

**Comment by marsella** [comment]
The issues here are turning a bit into a fix-transcripts list (since session ids are inherently tied to correct transcripts).

Here are the remaining fields of `sid` and `ssid` that are not yet raised in issues, but need to be incorporated into transcripts at some point in the protocol:
- `rid` and `i` need to be incorporated into the PiSch proof in key-gen
- `rid` and `X = (X1, ... , Xn)` need to be put into the "global"/parent transcript at the end of key-gen.
- `(N, s, t)` (all vectors) need to be added to the "global"/parent transcript at the end of aux-info. `Y` and `X*` would also be added if we were doing key refresh, but we can ignore them for now.

**Comment by marsella** [comment]
@Ra1issa , @indomitableSwan and I had a conversation about this task today. It was wide ranging; here are some of the takeaways:
- We agreed on terminology -- see notes in issue description. In particular, we agreed that the thing we call "session ID" is not the same as the `sid` or `ssid` they define in the paper; those values contain parameters and identifiers that will be captured and used appropriately via #149. When we say "session ID", we're just talking about a unique identifier that tags messages and goes into proofs to prevent replays.
- The most pressing question is, how do we generate session IDs in a way that all participants can be confident about their uniqueness (e.g. to prevent replay attacks). Uniqueness needs to scale once we move to the threshold setting.
- The potential generating parties are the coordinator and/or the participants (collectively). The asset owner is not a good choice.
- Open question: Are there cryptographic properties the session ID must satisfy, or does it just have to be unique? E.g. should we implement tools to define it within the library or could external parties select it?

The core question we'd like to answer is: Who creates the session ID, and how?
The action item is that Rawane is going to generate a proposal with a few potential solutions.

**Comment by marsella** [comment]
Clarification: We won't use the session id `sid` and subsession id `ssid` exactly as described in the paper. Those values include a bunch of contextual global parameters (ECDSA group, Paillier size, etc.) and session-specific parameters (Paillier public keys, public key shares, ring-Pedersen parameters, etc.).

In the paper, `sid` and `ssid` are used in two ways
1. to tag every message sent in a run of a subprotocol
2. to provide context to ZK proofs

In both cases, we want to enforce a uniqueness constraint, so that adversaries can reuse messages and proofs in a replay-style attack. In (2), we want to tightly bind the proof to the specific protocol instance, which requires both uniqueness and all the additional parameters for context.

In the implementation, we'll separate the two roles here (uniqueness and proof-binding) and incorporate them in different ways. The proof-binding work will be handled by #149. The uniqueness constraint is the problem we want to solve here: Who generates session IDs? How? and how is the uniqueness constraint enforced?
