### ISSUE TITLE
Clarify storage requirements

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/tss-ecdsa#92]
The library currently maintains a large amount of storage (of both inter-protocol intermediate stages and intra-protocol outputs) in memory. In order to deploy the library at a larger scale, we'll need to design a more sustainable storage solution that allows the calling application to make decisions about how long-term storage (at least) is maintained and implemented.

This epic has the following goals:
- [x] Do a deeper dive on the current state of stored values in the implementation, focusing particularly on separating intermediate states from a single subprotocol from outputs that are maintained between multiple subprotocol executions
- [x] Design an appropriate approach to storage that allows the calling application to make any meaningful decisions about long-term storage. This may involve making decisions about what a reasonable amount of information is to hold in memory. (See internal document "Using tss-ecdsa - API" for some early options).
- [x] ~Implement a storage API (if appropriate)~ Refactor long-term storage to remove it from the library and document storage requirements for long-term storage by the client API. The intended audience is a non-cryptographic engineer. Non-exhaustive list of things this should include: clear guidance on any security-critical elements, definition of which identifiers will be required to access a given type of data (see #91).
- [x] Refactor storage to improve overall code quality and guarantees.

### Terminology
The subprotocols are key generation, aux-info, pre-signing, and signing. I think in the immediate phases, we'll be grouping these into pairs (e.g. key generation will always be immediately followed by aux-info, ditto for pre-signing and signing). So when I write about intra-protocol operations, I mean data that is output by aux-info and used in pre-signing.

**Comment by marsella** [comment]
Here are some notes about the current state of storage, and some low-hanging fruit we can pick off to start to improve it.

There are two kinds of storage managed by a `Participant`: local storage and main storage. Local storage is maintained by the sub-participants (e.g. `AuxInfoParticipant`) and is documented to be for "storing secrets". It's not accessible outside the individual sub-participant, so I think it's used to store secrets and data between rounds of a single subprotocol. Main storage is maintained by the parent `Participant`. I think it stores public and private material used between subprotocols, including presign records, Paillier public keys, ring-Pedersen parameters, and public key shares (e.g. of the generated key) from all parties, and the Participant's own Paillier decryption key and private key share.

I think the following techniques are missing from storage:
- Main storage should be handled by the calling application, not maintained in memory by the `Participant`. We need to figure out an appropriate method for callers to provide their own storage (does a trait definition with the existing public methods do the trick?)
- Local storage could be handled either by the `Participant` or the calling application; let's assume we leave it to the `Participant`. In that case, we need to improve deletion. When a subprotocol finishes, all the local storage associated with that subprotocol should also be deleted. The calling application should also be able to purge messages that were received but not processed, with some timeout of their choosing (e.g. an aborted protocol or just singleton messages that weren't part of a complete protocol run -- due to malicious behavior, weird network dropping, etc.). Main storage deletes presign records when they're used, and everything else is ok to persist over the lifetime of a `Participant`, I think.

There is some opportunity to clean up the way that protocols interact with storage right now. These items are lower priority and might be obviated by the above, but I'm noting them because I've thought about them.
- Simplify ser/deserialization in local storage. There are a fixed set of storable keys; each key is associated with one data type (the type of the thing being stored). Right now, the caller has to manually serialize the data to insert, then try deserialize the stored bytes into the correct data type to retrieve. Can this just be handled internally by the storage module?
- There should be a method to copy from one `Storage` to another. Right now, we manually do this to copy things from local to main storage at the end of a protocol. If we add a storage trait, we should put a `transfer(&self, &other: Storage)` method on it to copy over specific items.
- Refactoring subprotocol implementations: I was considering that I'd find easier to read the protocols if each round was contained in a single function. At the beginning, we called out to a "check if we're ready" function, and if so, to a retrieval method  to get everything out of local and main storage that we'll need to execute that round. Then at the end, we call to a storage method that puts everything we want to maintain back into storage.

**Comment by gatoWololo** [comment]
> (e.g. key signing will always be immediately followed by aux-info, ditto for pre-signing and signing).

Should key signing be key generation here?

**Comment by marsella** [comment]
> > (e.g. key signing will always be immediately followed by aux-info, ditto for pre-signing and signing).
> 
> Should key signing be key generation here?

Ahh, yes! Fixed.
